version: '3'

services:
  web1:
    build:
      context: ./web1
    ports:
      - "80"

  web2:
    build:
      context: ./web2
    ports:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2